import os
import sys
import subprocess

# TrueColor (24-bit) RGB match for PowerShell's command yellow
PEACH = '\033[38;2;245;231;158m'

def check_dependencies():
    try:
        import bs4
        import httpx
        import pwinput
        import colorama
    except ImportError as e:
        print(f"\n   [!] Missing required module: {e.name}")
        print("   [.] Running First-Time Setup: Installing dependencies...")
        print("   [.] This will only happen once. Please wait...\n")
        
        try:
            subprocess.check_call(
                [sys.executable, "-m", "pip", "install", "-r", "requirements.txt", "playwright", "install", "chromium", "--quiet"]
            )
            subprocess.check_call([sys.executable, "-m", "pip", "install", "colorama", "--quiet"])
            
            print("\n   [✓] Dependencies installed successfully!")
            print("   [+] Launching VTOP CLI...\n")
            os.execv(sys.executable, ['python'] + sys.argv)
            
        except subprocess.CalledProcessError:
            print("\n   [x] Auto-install failed.")
            print("   [!] Please run 'pip install -r requirements.txt' manually.")
            sys.exit(1)

check_dependencies()

from colorama import init, Fore, Back, Style
init(autoreset=True) # Initialize Colors

import argparse
import requests
import asyncio
import json
import time
import getpass
import traceback
import glob
import re
import math
from datetime import datetime as dt 
from vitap_vtop_client.client import VtopClient
from services import *

# --- Configuration ---
CURRENT_VERSION = "5.2.0"

def check_for_updates():
    # Imports kept inside so the updater is 100% self-contained
    import urllib.request
    import json
    import os
    import sys
    import time
    import zipfile  
    import io       

    API_URL = "https://api.github.com/repos/vrmanideep/vtop/releases/latest"
    print(f"   {Fore.CYAN}[.] Checking for updates...", end="\r") 
    
    try:
        req = urllib.request.Request(API_URL, headers={'User-Agent': 'vtop-updater'})
        with urllib.request.urlopen(req, timeout=3) as response:
            data = json.loads(response.read().decode('utf-8'))
            
        tag_name = data['tag_name'] 
        remote_version = tag_name.replace('v', '') 
        changelog = data['body']
        zipball_url = data['zipball_url'] 
        
        if remote_version != CURRENT_VERSION:
            print(" " * 50, end="\r")
            print(f"   {Fore.RED}[!] UPDATE AVAILABLE: v{CURRENT_VERSION} -> v{remote_version}")
            print(f"\n{Fore.CYAN}--- Release Notes ---")
            print(f"{Fore.WHITE}{changelog}")
            print(f"{Fore.CYAN}---------------------\n")
            
            choice = input(f"   {PEACH}Download now? (y/n): {Fore.WHITE}").lower().strip()
            if choice == 'y':
                print(f"   {Fore.CYAN}[.] Downloading update via Zipball...", end="\r")
                try:
                    # --- THE BULLETPROOF PATH FIX ---
                    # 1. Get the exact, absolute directory where THIS script is currently sitting
                    script_dir = os.path.dirname(os.path.abspath(sys.argv[0]))
                    
                    zip_req = urllib.request.Request(zipball_url, headers={'User-Agent': 'vtop-updater'})
                    with urllib.request.urlopen(zip_req, timeout=15) as response:
                        zip_data = response.read()
                        
                    with zipfile.ZipFile(io.BytesIO(zip_data)) as z:
                        for file_info in z.infolist():
                            if file_info.is_dir(): continue
                            
                            # Skip the root folder name generated by GitHub's zipball
                            parts = file_info.filename.split('/', 1)
                            if len(parts) > 1 and parts[1]:
                                target_relative_path = parts[1]
                                
                                # 2. Force the extraction directly into the absolute script directory
                                target_absolute_path = os.path.join(script_dir, target_relative_path)
                                
                                folder_name = os.path.dirname(target_absolute_path)
                                if folder_name: os.makedirs(folder_name, exist_ok=True)
                                
                                with open(target_absolute_path, 'wb') as f_out:
                                    f_out.write(z.read(file_info.filename))
                                    
                    print(f"\n   {Fore.GREEN}[✓] Update complete! Restarting...            \n")
                    time.sleep(1.5) 
                    sys.stdout.flush()
                    os.system('cls' if os.name == 'nt' else 'clear')
                    
                    # --- THE BULLETPROOF RESTART FIX ---
                    # 3. Force Python to execute the absolute path of the newly updated script
                    script_path = os.path.abspath(sys.argv[0])
                    os.execv(sys.executable, [sys.executable, script_path] + sys.argv[1:])
                    
                except Exception as e:
                    print(f"\n   {Fore.RED}[x] Failed to extract files: {e}")
        else:
            print(" " * 50, end="\r")
    except Exception:
        print(" " * 50, end="\r")

def get_cred(file_path="credentials.txt"):
    if os.path.exists(file_path):
        with open(file_path, "r") as f:
            lines = [line.strip() for line in f.readlines() if line.strip()]
            if len(lines) >= 2:
                return lines[0], lines[1]
            else:
                print(f"\n   {Fore.RED}[!] {file_path} is corrupted (needs 2 lines). Let's fix it.")

    print(f"\n   {PEACH}=======================================")
    print(f"   {PEACH}[ FIRST TIME SETUP: VTOP CLI ]")
    print(f"   {PEACH}=======================================")
    print(f"   {Fore.WHITE}Let's set up your {file_path} file securely.\n")
    
    while True:
        username = input(f"   {PEACH}[>] Enter Registration Number (e.g., 21BCExxxx): {Fore.WHITE}").strip().upper()
        password = pwinput.pwinput(prompt=f"   {PEACH}[>] Enter VTOP Password: {Fore.WHITE}", mask="*").strip()
        
        if not username or not password:
            print(f"   {Fore.RED}[!] Fields cannot be empty. Try again.\n")
            continue

        print(f"\n   {Fore.CYAN}--- Verify Your Details ---")
        print(f"   {Fore.WHITE}Registration No: {username}")
        print(f"   {Fore.WHITE}Password:        {'*' * len(password)}")
        
        confirm = input(f"\n   {PEACH}Save these credentials and login? (y/n): {Fore.WHITE}").strip().lower()
        
        if confirm == 'y':
            with open(file_path, "w") as f:
                f.write(f"{username}\n{password}\n")
            print(f"   {Fore.GREEN}[✓] {file_path} created successfully!\n")
            return username, password
        else:
            print(f"   {Fore.RED}[!] Setup cancelled. Let's try typing that again.\n")

get_credentials = get_cred
a, password = get_cred("credentials.txt")

# SSL BYPASS
_original_init = httpx.AsyncClient.__init__
def _patched_init(self, *args, **kwargs):
    kwargs['verify'] = False
    _original_init(self, *args, **kwargs)
httpx.AsyncClient.__init__ = _patched_init

async def vtopClientLogin(client: VtopClient) -> bool:
    try:
        await client._perform_login_sequence()
        return True
    except Exception as e:
        print(f"{Fore.RED}Login Failed: {e}")
        return False

async def download_material(client, url_suffix, filename):
    return await download_gate_pass(client, url_suffix, filename)

def print_header(title):
    print(f"\n{PEACH}{Style.BRIGHT}{title}")
    print(f"{Fore.CYAN}{'=' * 60}")

def print_profile(data):
    if not data or not data.get("basic"):
        print(f"   {PEACH}(No profile data found)")
        return
    b = data["basic"]
    print(f"\n   {PEACH}{Style.BRIGHT}{'STUDENT PROFILE':^60}")
    print(f"   {Fore.CYAN}" + "=" * 60)
    print(f"   {Fore.CYAN}{'Name':<15} : {Fore.WHITE}{b.get('name')}")
    print(f"   {Fore.CYAN}{'Reg No':<15} : {Fore.WHITE}{b.get('regno')}")
    print(f"   {Fore.CYAN}{'Program':<15} : {Fore.WHITE}{b.get('program')}")
    print(f"   {Fore.CYAN}{'VIT Email':<15} : {Fore.WHITE}{b.get('vitemail')}")
    print(f"   {Fore.CYAN}{'Mobile':<15} : {Fore.WHITE}{b.get('mobile')}")
    print(f"   {Fore.CYAN}" + "-" * 60)
    p = data.get("proctor")
    if p and p.get("Name"):
        print(f"\n   {PEACH}{Style.BRIGHT}{'PROCTOR INFORMATION':^60}")
        print(f"   {Fore.CYAN}" + "=" * 60)
        fields = [("Name", "Name"), ("ID", "Faculty ID"), ("Email", "Email"), ("Mobile", "Mobile"), ("Cabin", "Cabin")]
        for label, key in fields:
            if key in p:
                print(f"   {Fore.CYAN}{label:<15} : {Fore.WHITE}{p[key]}")
    else:
        print(f"\n   {PEACH}[!] Proctor Information section was not found or is empty.")
    print(f"   {Fore.CYAN}" + "=" * 60 + "\n")

def print_grade_history(data):
    if not data or not data.get("courses"):
        print(f"\n   {Fore.RED}[!] No grade history found.")
        return
    print(f"\n   {PEACH}{Style.BRIGHT}ACADEMIC TRANSCRIPT")
    print(f"   {Fore.CYAN}" + "─" * 95)
    print(f"   {Fore.CYAN}{'CODE':<15} {'GRADE':<12} {'CREDITS':<12} {'COURSE NAME'}")
    print(f"   {Fore.CYAN}" + "─" * 95)
    for c in data["courses"]:
        grade = c['grade']
        g_color = Fore.GREEN if grade in ['S', 'A'] else (Fore.RED if grade == 'F' else PEACH)
        print(f"   {Fore.WHITE}{c['code']:<15} {g_color}{grade:<12} {Fore.WHITE}{c['credits']:<12} {c['name']}")
    print(f"   {Fore.CYAN}" + "─" * 95 + "\n")
    s = data.get("summary", {})
    print(f"   {PEACH}ACADEMIC STANDING (OVERALL)")
    print(f"   {Fore.CYAN}-------------------------------------------")
    print(f"   {Fore.CYAN}CURRENT CGPA          : {Fore.GREEN}{Style.BRIGHT}{s.get('cgpa')}")
    print(f"   {Fore.CYAN}CREDITS EARNED        : {Fore.WHITE}{s.get('earned')}")
    print(f"   {Fore.CYAN}CREDITS REGISTERED    : {Fore.WHITE}{s.get('registered')}")
    print(f"   {Fore.CYAN}-------------------------------------------\n")

def print_timetable(data):
    if not data:
        print(f"   {PEACH}(No timetable found)")
        return
        
    # Adjusted column widths to fit the new course types and potentially longer venues
    print(f"   {Fore.CYAN}{'TIME':<15} {'VENUE':<12} {'CODE (TYPE)':<16} {'SLOT':<15} {'COURSE NAME'}")
    print(f"   {Fore.CYAN}" + "=" * 110)
    
    day_order = {"MONDAY": 1, "TUESDAY": 2, "WEDNESDAY": 3, "THURSDAY": 4, "FRIDAY": 5, "SATURDAY": 6, "SUNDAY": 7}
    sorted_days = sorted(data.keys(), key=lambda d: day_order.get(d.upper(), 99))
    
    for day in sorted_days:
        classes = data[day]
        if not isinstance(classes, list) or not classes: 
            continue
            
        print(f"   {PEACH}{Style.BRIGHT}[{day.upper()}]")
        
        # Safely sort using the explicit 'start_time' parsed from the new backend
        try: 
            classes.sort(key=lambda x: x.get('start_time', '23:59'))
        except Exception: 
            pass
            
        for c in classes:
            time_str = c.get('time', '-')        
            venue    = c.get('venue', '-')       
            code     = c.get('course_code', '-') 
            c_type   = c.get('course_type', '') 
            name     = c.get('course_name', '-') 
            slot     = c.get('slot', '-')        
            
            # Clean up trailing hyphens from the slot parser
            if slot.endswith('-'): 
                slot = slot[:-1].strip()
                
            # Combine Course Code and Type (e.g., CSE1005 (ETH))
            code_display = f"{code} ({c_type})" if c_type else code
                
            print(f"   {Fore.WHITE}{time_str:<15} {venue:<12} {Fore.GREEN}{code_display:<16} {PEACH}{slot:<15} {Fore.WHITE}{name}")
            
        print(f"   {Fore.CYAN}{'-' * 110}")

def print_today_schedule(data):
    if not data:
        print(f"   {PEACH}(No timetable data available)")
        return

    current_day_upper = dt.now().strftime("%A").upper() 
    current_day_title = dt.now().strftime("%A").title()
    
    print(f"\n   {PEACH}{Style.BRIGHT}{'SCHEDULE FOR ' + current_day_upper:^60}")
    print(f"   {Fore.CYAN}" + "=" * 80)
    classes = data.get(current_day_title) or data.get(current_day_upper) or []
    if not classes:
        print(f"   {Fore.GREEN}[OK] No classes scheduled for {current_day_title}!")
        print(f"   {Fore.CYAN}" + "=" * 80)
        return
    try: 
        classes.sort(key=lambda x: x.get('time', '23:59').split('-')[0].strip())
    except: pass
    
    print(f"   {Fore.CYAN}{'TIME':<15} {'VENUE':<8} {'CODE':<10} {'SLOT':<14} {'COURSE NAME'}")
    print(f"   {Fore.CYAN}" + "-" * 100)
    for c in classes:
        time_str = c.get('time', '-')        
        venue    = c.get('venue', '-')       
        code     = c.get('course_code', '-') 
        name     = c.get('course_name', '-')[:60]
        slot     = c.get('slot', '-')        
        if slot.endswith('-'): slot = slot[:-1].strip()
        print(f"   {Fore.WHITE}{time_str:<15} {venue:<8} {Fore.GREEN}{code:<10} {PEACH}{slot:<15} {Fore.WHITE}{name}")
    print(f"   {Fore.CYAN}" + "-" * 100)

async def print_attendance_with_details(client, semester_id, summary_data):
    if not summary_data:
        print(f"   {PEACH}(No data found)")
        return
    print(f"\n   {PEACH}{Style.BRIGHT}{'ATTENDANCE REPORT (Detailed History)':^80}")
    print(f"   {Fore.CYAN}" + "=" * 80)
    for sub in summary_data:
        code = sub.get('course_code', '-')
        name = sub.get('course_name', '-')
        ctype = sub.get('course_type', '-')
        perc = sub.get('percentage', '0')
        attended = sub.get('attended', '0')
        total = sub.get('total', '0')
        try: is_low = float(perc) < 75
        except: is_low = False
        
        p_color = Fore.RED if is_low else Fore.GREEN
        
        print(f"\n    {Fore.WHITE}{name} ({ctype})")
        print(f"        {Fore.WHITE}Attendance: {p_color}{perc}% {Fore.WHITE}({attended}/{total})")
        c_id = sub.get('course_id')
        type_id = sub.get('type_id') 
        if not type_id: type_id = sub.get('type_code')
        if c_id and type_id:
            try:
                history = await fetchAttendanceDetail(client, semester_id, c_id, type_id)
                if history:
                    def parse_date(x):
                        try: return dt.strptime(x['date'], "%d-%b-%Y")
                        except: 
                            try: return dt.strptime(x['date'], "%d-%m-%Y")
                            except: return dt.min 
                
                    history.sort(key=parse_date)
                    last_date = history[-1].get('date', 'N/A')
                    print(f"        {Fore.CYAN}Attendance Last Updated on: {Fore.WHITE}{last_date}")
                    
                    exceptions = [h for h in history if "Present" not in h['status']]
                    
                    if exceptions: 
                        print(f"        {PEACH}[!] Found {len(exceptions)} Absences/On Duty:")
                        print(f"            {Fore.CYAN}{'DATE':<12} {'DAY':<5} {'SLOT':<8} {'STATUS'}") 
                        print(f"            {Fore.CYAN}" + "-" * 40)
                        exceptions.sort(key=parse_date, reverse=True)
                        
                        for h in exceptions:
                            date_str = h.get('date', '-')
                            day_name = "-"
                            try:
                                d_obj = parse_date(h)
                                if d_obj != dt.min:
                                    day_name = d_obj.strftime("%a")
                            except: pass
                            
                            c_stat = Fore.GREEN if "On Duty" in h['status'] else Fore.RED
                            print(f"            {Fore.WHITE}{date_str:<12} {day_name:<5} {h['slot']:<8} {c_stat}{h['status']}")
                    else:
                          print(f"        {Fore.GREEN}(History fetched: {len(history)} classes, All Present)")
                else:
                    print(f"        {PEACH}(No history records found)")
            except Exception as e:
                print(f"        {Fore.RED}[!] Detail fetch error: {e}")
        else:
            print(f"        {Fore.RED}[!] Cannot fetch details (ID missing).")
        print(f"   {Fore.CYAN}" + "-" * 50)

def print_attendance(data):
    if not data:
        print(f"   {PEACH}(No data found)")
        return
    print(f"\n   {Fore.CYAN}{'S.No':<5} {'CODE':<9} {'FACULTY':<30} {'TYPE':<10} {'SLOT':<15} {'%':<5} {'STATUS'}")
    print(f"   {Fore.CYAN}" + "─" * 90)
    for i, sub in enumerate(data):
        code = sub.get('course_code', '-')
        faculty = sub.get('faculty_name', 'N/A')
        if len(faculty) > 30: faculty = faculty[:28] + ".."
        ctype = sub.get('course_type', '').replace("Embedded Theory", "Emb Th").replace("Embedded Lab", "Emb Lab").replace("Theory Only", "Theory")
        raw_slot = sub.get('course_slot') or sub.get('slot') or '-'
        if ' - ' in raw_slot: slot = raw_slot.split(' - ')[1] 
        else: slot = raw_slot
        perc = sub.get('attendance_percentage', '0')
        if perc == '0': perc = sub.get('percentage', '0')
        try: 
            is_low = float(perc) < 75
            status = f"{Fore.RED}[LOW]" if is_low else f"{Fore.GREEN}[OK]"
            p_col = Fore.RED if is_low else Fore.GREEN
        except: 
            status = "-"
            p_col = Fore.WHITE
            
        print(f"   {Fore.WHITE}{i+1:<5} {code:<9} {faculty:<30} {ctype:<10} {slot:<15} {p_col}{perc:<5} {status}")
    print(f"   {Fore.CYAN}" + "─" * 90)

def print_marks(data):
    if not data or "courses" not in data:
        print(f"   {PEACH}(No marks found)")
        return
    courses = data["courses"]
    courses.sort(key=lambda x: x.get('course_code', ''))
    
    print(f"\n   {Fore.CYAN}{'CODE':<10} {'COURSE TITLE':<60} {'MARK TITLE':<40} {'SCORE':<8} {'MAX':<6} {'WGT%':<6} {'WGT MRK'}")
    print(f"   {Fore.CYAN}" + "━" * 145)
    
    for course in courses:
        code = course.get('course_code', '-')
        title = course.get('course_title', '-')[:58]
        details = course.get('details', [])
        
        if not details:
             print(f"   {Fore.WHITE}{code:<10} {title:<60} {'-':<40} {'-':<8} {'-':<6} {'-':<6} {'-'}")
             print(f"   {Fore.CYAN}" + "-" * 145)
             continue
             
        first_line = True
        for mark in details:
            m_title = mark.get('mark_title', '-')[:38] 
            score   = str(mark.get('scored_mark', '-'))
            max_m   = str(mark.get('max_mark', '-'))
            w_pct   = str(mark.get('weightage_pct', '-'))
            w_mrk   = str(mark.get('weightage_mark', '-'))
            
            s_color = Fore.RED if score == "ABSENT" else Fore.GREEN
            
            if first_line:
                print(f"   {Fore.WHITE}{code:<10} {title:<60} {m_title:<40} {s_color}{score:<8} {Fore.WHITE}{max_m:<6} {w_pct:<6} {w_mrk}")
                first_line = False
            else:
                print(f"   {Fore.WHITE}{'':<10} {'':<60} {m_title:<40} {s_color}{score:<8} {Fore.WHITE}{max_m:<6} {w_pct:<6} {w_mrk}")
                
        print(f"   {Fore.CYAN}" + "-" * 145)

def print_exam_schedule(data):
    if not data:
        print(f"   {PEACH}(No exams scheduled)")
        return

    def parse_date(d):
        try: return dt.strptime(d, "%d-%b-%Y")
        except: return dt.max

    cat_priority = {"FAT": 0, "CAT2": 1, "CAT1": 2}
    
    try:
        data.sort(key=lambda x: (
            cat_priority.get(x.get('category', 'FAT'), 3),
            parse_date(x.get('exam_date', ''))             
        ))
    except: pass

    print(f"\n   {Fore.CYAN}{'COURSE' :<10} {'': <60} {'COURSE':<6} {'':<16} {'':<18} {'EXAM' :<10} {'EXAM' :<8} {'' :<20} {'':<12} {'SEAT' :<7} {'SEAT'}")
    print(f"   {Fore.CYAN}{'CODE' :<25} {'COURSE TITLE' :<46} {'TYPE' :<8} {'CLASS ID' :<14} {'SLOT':<17} {'DATE' :<9} {'SESSION':<15} {'EXAM TIME' :<17} {'VENUE':<7} {'LOCATION':<10} {'NO.'}")
    print(f"   {Fore.CYAN}" + "─" * 182)

    current_cat = None
    for ex in data:
        cat = ex.get('category', 'FAT')
        
        if cat != current_cat:
            display_cat = cat
            if cat == "CAT1": display_cat = "CAT- 1"
            elif cat == "CAT2": display_cat = "CAT- 2"
            
            if display_cat in ["CAT- 1", "CAT- 2"]: 
                print(f"\n   {PEACH}{'-'*84} {display_cat} EXAMS {'-'*84}\n")
            else :
                print(f"\n   {PEACH}{'-'*85} {display_cat} EXAMS {'-'*86}\n")
                
            current_cat = cat
        
        code  = ex.get('course_code', '-')
        title = ex.get('course_title', '-')[:58] 
        etype = ex.get('exam_type', '-')
        cid   = ex.get('class_id', '-')
        slot  = ex.get('slot', '-')
        date  = ex.get('exam_date', '-')
        sess  = ex.get('session', '-')
        
        time_str = ex.get('exam_time', '-') 
        if time_str in [None, "", "-"]: time_str = "-"
        
        venue = ex.get('venue', '-')
        sloc  = ex.get('seat_location', '-')
        seat  = ex.get('seat_number', '-')

        if seat in ["", "-"]: seat = "-"
        if venue in ["", "-"]: venue = "-"
        if sloc in ["", "-"]: sloc = "-"

        print(f"   {Fore.GREEN}{code:<10} {Fore.WHITE}{title:<60} {etype:<6} {cid:<16} {PEACH}{slot:<15} {PEACH}{date:<14} {Fore.WHITE}{sess:<8} {time_str:<22} {Fore.WHITE}{venue:<8} {PEACH}{sloc:<10} {seat}")

    print(f"   {Fore.CYAN}" + "─" * 182)

def print_credits(data):
    if not data:
        print(f"   {PEACH}(No credit details found)")
        return
    print(f"\n   {Fore.CYAN}{'CATEGORY':<25} {'EARNED':<8} {'TOTAL':<8} {'PROGRESS'}")
    print(f"   {Fore.CYAN}" + "─" * 65)
    total_earned = 0
    total_required = 0
    for item in data:
        cat = item['category']
        earned = item['earned']
        total = item['total']
        pct = item['percent']
        if "Total" in cat: continue
        total_earned += earned
        total_required += total
        bar_len = 15
        filled = int((pct / 100) * bar_len)
        bar = f"{Fore.GREEN}█{Fore.WHITE}" * filled + "░" * (bar_len - filled)
        print(f"   {Fore.WHITE}{cat:<25} {earned:<8.1f} {total:<8.0f} {bar} {int(pct)}%")
    print(f"   {Fore.CYAN}" + "─" * 65)
    tot_pct = (total_earned / total_required * 100) if total_required > 0 else 0
    bar_len = 15
    filled = int((tot_pct / 100) * bar_len)
    bar = f"{Fore.GREEN}█{Fore.WHITE}" * filled + "░" * (bar_len - filled)
    print(f"   {Fore.CYAN}{'TOTAL CREDITS':<25} {Fore.GREEN}{total_earned:<8.1f} {Fore.WHITE}{total_required:<8.0f} {bar} {int(tot_pct)}%")
    print(f"   {Fore.CYAN}" + "─" * 65)

def print_course_page_table(data):
    if not data:
        print(f"\n   {Fore.RED}[!] No data received from Course Page.")
        return

    meta = data.get("metadata", {})
    if meta:
        print(f"\n   {PEACH}{Style.BRIGHT}COURSE: {Fore.WHITE}{meta.get('code')} - {meta.get('title')}")
        print(f"   {PEACH}{Style.BRIGHT}SLOT: {Fore.WHITE}{meta.get('slot')} | {PEACH}{Style.BRIGHT}FACULTY: {Fore.WHITE}{meta.get('faculty')}")
        print(f"   {Fore.CYAN}" + "─" * 105)

    found = False
    if data.get("general"):
        found = True
        print(f"\n   {Fore.CYAN}GENERAL MATERIALS")
        print(f"   {Fore.CYAN}" + "-" * 60)
        for i, item in enumerate(data["general"]):
            print(f"   {PEACH}[G{i+1}] {Fore.WHITE}{item['title']:<60} {Fore.GREEN}[AVAILABLE]")

    if data.get("lectures"):
        found = True
        print(f"\n   {Fore.CYAN}{'S.NO':<5} {'DATE':<12} {'DAY':<5} {'TOPIC':<100} {'MATERIALS'}")
        print(f"   {Fore.CYAN}" + "─" * 145)
        
        for lec in data["lectures"]:
            s_no = lec['s_no']
            date = lec['date']
            day = lec['day']
            topic = lec['topic'][:98]
            
            assets = []
            if lec.get('download_path'): assets.append(f"{Fore.GREEN}Main{Fore.WHITE}")
            if lec.get('ref_paths'): assets.append(f"{PEACH}{len(lec['ref_paths'])} Refs{Fore.WHITE}")
            if lec.get('web_links'): assets.append(f"{Fore.BLUE}{len(lec['web_links'])} Web{Fore.WHITE}")
            
            mat = ", ".join(assets) if assets else "-"
            
            print(f"   {PEACH}{s_no:<5} {Fore.WHITE}{date:<12} {day:<5} {topic:<100} {mat}")
            
        print(f"   {Fore.CYAN}" + "─" * 145)
    
    if not found:
        print(f"\n   {PEACH}(No course data found. Check if the course page loaded correctly.)")

def printGeneralOuting(history):
    if not history:
        print(f"\n   {PEACH}(No history found)")
        return

    header = (
        f"\n   {Fore.CYAN}{'#':<3} "
        f"{'OUT DATE':<11} {'TIME':<9} "
        f"{'PLACE':<20} "
        f"{'PURPOSE':<25} "
        f"{'IN DATE':<11} {'TIME':<9} "
        f"{'STATUS':<14} {'PASS'}"
    )
    
    print(header)
    print(f"   {Fore.CYAN}" + "─" * 120) 

    for i, h in enumerate(history):
        status_raw = h['status'].strip()
        status_lower = status_raw.lower()
        
        if "accepted" in status_lower or "approved" in status_lower:
            stat_display = f"{Fore.GREEN}Approved{Fore.WHITE}"
        elif "rejected" in status_lower:
            stat_display = f"{Fore.RED}Rejected{Fore.WHITE}"
        elif "mentor" in status_lower and "waiting" in status_lower:
            stat_display = f"{PEACH}Wait: Mentor{Fore.WHITE}"
        elif "warden" in status_lower and "waiting" in status_lower:
            stat_display = f"{PEACH}Wait: Warden{Fore.WHITE}"
        else:
            stat_display = status_raw[:15]

        pass_display = f"{Fore.GREEN}YES{Fore.WHITE}" if h.get('download_url') else "NO"

        def trunc(text, length):
            text = text.replace('\n', ' ').strip()
            return (text[:length-2] + '..') if len(text) > length else text

        def short_date(d): 
            return d[:-4] + d[-2:] if len(d) > 10 else d

        out_d = short_date(h['out_date'])
        in_d  = short_date(h['in_date'])
        
        place = trunc(h['place'], 20)
        purp  = trunc(h['purpose'], 25)

        print(
            f"   {Fore.WHITE}{i+1:<3} "
            f"{out_d:<11} {h['out_time']:<9} "
            f"{place:<20} "
            f"{purp:<25} "
            f"{in_d:<11} {h['in_time']:<9} "
            f"{stat_display:<24} {pass_display}"
        )

    print(f"   {Fore.CYAN}" + "─" * 120)

def printWeekendOuting(history):
    if not history:
        print(f"\n   {PEACH}(No history found)")
        return

    header = (
        f"\n   {Fore.CYAN}{'#':<3} {'BLK':<6} {'ROOM':<6} {'PURPOSE':<20} "
        f"{'TIME':<16} {'DATE':<12} {'STATUS':<10} {'OUTPASS'}"
    )
    
    print(header)
    print(f"   {Fore.CYAN}" + "─" * 95) 

    for idx, h in enumerate(history):
        status_lower = h['status'].lower()
        
        if "accepted" in status_lower or "approved" in status_lower:
            stat_display = f"{Fore.GREEN}Approved{Fore.WHITE}"
        elif "rejected" in status_lower:
            stat_display = f"{Fore.RED}Rejected{Fore.WHITE}"
        elif "wait" in status_lower or "warden" in status_lower:
            stat_display = f"{PEACH}Wait: Warden{Fore.WHITE}"
        else:
            stat_display = h['status'][:15]

        def trunc(text, length):
            text = text.replace('\n', ' ').strip()
            return (text[:length-2] + '..') if len(text) > length else text

        dl_avail = f"{Fore.GREEN}YES{Fore.WHITE}" if h['download_link'] else f"{Fore.RED}NO{Fore.WHITE}"

        print(
            f"   {Fore.WHITE}{idx+1:<3} {h['block']:<6} {h['room']:<6} "
            f"{trunc(h['purpose'], 20):<20} {trunc(h['out_time'], 16):<16} "
            f"{h['out_date']:<12} {stat_display:<20} {dl_avail}"
        )

    print(f"   {Fore.CYAN}" + "─" * 95)
    
async def main():
    global asyncio
    
    while True:
        reg_no, password = get_credentials("credentials.txt")
        print(f"\n{Fore.CYAN}[.] Connecting to V-TOP as {reg_no}...")
        
        login_success = False
        
        async with VtopClient(reg_no, password) as client:
            try:
                if await vtopClientLogin(client):
                    login_success = True
                else:
                    print(f"   {Fore.RED}[x] Server rejected the connection.")
            except Exception as e:
                print(f"   {Fore.RED}[x] Fatal Connection Crash: {e}")

            if not login_success:
                print(f"\n{Fore.RED}[!] LOGIN FAILED. The VTOP server timed out, or your password is wrong.")
                action = input(f"{PEACH}[-] [ENTER] Retry | [0/EXIT] Close | [WIPE] Delete Saved Pass: {Fore.WHITE}").strip().upper()
                
                if action in ['EXIT', '0']:
                    print(f"{PEACH}Exiting... See you later!")
                    import sys
                    sys.exit() 
                elif action == 'WIPE':
                    import os
                    if os.path.exists("credentials.txt"):
                        os.remove("credentials.txt")
                    print(f"{PEACH}[-] Trashed credentials. Let's try again...\n")
                
                continue

            print(f"   {Fore.CYAN}[.] Entering Home Page...")
            home_success = False
            
            for attempt in range(1, 4):
                try:
                    import httpx
                    content_resp = await client._client.get(
                        "https://vtop.vitap.ac.in/vtop/content?", 
                        timeout=25.0,
                        follow_redirects=True
                    )
                    if content_resp.status_code == 200:
                        home_success = True
                        break
                except Exception as e:
                    print(f"   {PEACH}[!] Connection timeout. Retrying landing page ({attempt}/3)...")
                    await asyncio.sleep(2)
            
            if not home_success:
                print(f"   {Fore.RED}[x] The VTOP server dropped the connection. Rebuilding socket...")
                continue 

            try:
                available_sems = await fetchSemesters(client)
                profile_data = await fetchProfile(client)
                
                if not available_sems:
                    print(f"   {Fore.RED}[x] Server returned empty semester data. Rebuilding...")
                    continue
            except Exception as e:
                print(f"   {Fore.RED}[x] Connection broke while scraping data: {e}")
                continue 
            await asyncio.sleep(0.5)
            student_name = profile_data.get("basic", {}).get("name", "Student")
            
           # --- SEMESTER AUTO-SELECTION (LOCAL CACHE) ---
            target_sem = available_sems[0]['id'] if available_sems else None
            current_sem_name = available_sems[0]['name'] if available_sems else "None"
            
            if available_sems and len(available_sems) > 1:
                import json
                from datetime import datetime
                import os
                
                try:
                    if os.path.exists("bunk_cache.json"):
                        with open("bunk_cache.json", "r") as f:
                            cache = json.load(f)
                            
                        sem_starts = cache.get("semester_starts", {})
                        
                        # Check if the upcoming semester has a registered start date in our JSON
                        if current_sem_name in sem_starts:
                            start_date_str = sem_starts[current_sem_name]
                            start_date = datetime.strptime(start_date_str, "%Y-%m-%d").date()
                            today = datetime.now().date()
                            
                            # If today is BEFORE the start date, drop to index 1
                            if today < start_date:
                                print(f"   {PEACH}[!] '{current_sem_name}' starts on {start_date_str}. Auto-switching to active...")
                                target_sem = available_sems[1]['id']
                                current_sem_name = available_sems[1]['name']
                except Exception as e:
                    pass # Fail silently and stick to index 0 if JSON is corrupted or missing
            # ---------------------------------------------------
            
            print(f"\n{Fore.CYAN}{'-'*65}\n")
            
            print(f"\n{Fore.CYAN}{'-'*65}\n")
            print(f" {Fore.WHITE}NAME:       : {Fore.GREEN}{student_name}")
            print(f" {Fore.WHITE}REG NO      : {Fore.CYAN}{reg_no}")
            print(f" {Fore.WHITE}CURRENT SEM : {PEACH}{current_sem_name}")
            print(f"{Fore.CYAN}{'-'*65}\n")
            
            while True:
                print_header("MAIN MENU")
                print(f"   {Fore.CYAN}" + "─" * 40)
                
                print(f"   {PEACH}[ ACADEMICS ]")
                print(f"   {Fore.WHITE}1.  Today's Schedule")
                print(f"   {Fore.WHITE}2.  Full Timetable")
                print(f"   {Fore.WHITE}3.  Attendance Record")
                print(f"   {Fore.WHITE}4.  Course Page")
                print(f"   {Fore.WHITE}5.  Internal Marks")
                print(f"   {Fore.WHITE}6.  Exam Schedule")
                print(f"   {Fore.WHITE}7.  Grade History (Transcript)")
                print(f"   {Fore.WHITE}8.  Digital Assignments")
                print(f"   {Fore.WHITE}9.  Credits Distribution")
                
                print(f"\n   {PEACH}{Style.BRIGHT}[ HOSTEL ]")
                print(f"   {Fore.WHITE}10. General Outing")
                print(f"   {Fore.WHITE}11. Weekend Outing")
                
                print(f"\n   {PEACH}{Style.BRIGHT}[ TOOLS ]")
                print(f"   {Fore.WHITE}12. Attendance Calculator")
                print(f"   {Fore.WHITE}13. Student Profile")
                print(f"   {Fore.WHITE}14. Change Semester")
                print(f"   {Fore.WHITE}15. Update Credentials")
                print(f"   {Fore.WHITE}16. Bunk Predictor (Simulate Absences)")
                print(f"   {Fore.WHITE}17. Open VTOP in Browser")

                print(f"\n   {Fore.RED}0.  Exit")
                print(f"   {Fore.CYAN}" + "─" * 40)
                
                print("", end="\n", flush=True)
                choice = input(f"   {PEACH}Select Option {Fore.WHITE}[1-17, or 'r' to Sync]: {Style.RESET_ALL}").strip().lower()
                
                # --- THE SYNC SHORTCUT ---
                if choice in ['r', 'sync', 'refresh']:
                    print(f"\n   {Fore.CYAN}[.] Force syncing all data with VTOP...")
                    try:
                        # 1. Re-fetch Profile (Optional, usually doesn't change, but good for completeness)
                        print(f"   {Fore.CYAN}    -> Fetching Profile...", end="\r")
                        profile_data = await fetchProfile(client)
                        print(f"   {Fore.GREEN}    -> Profile Synced!    ")

                        # 2. Re-fetch Timetable (Pass your current target_sem)
                        print(f"   {Fore.CYAN}    -> Fetching Timetable...", end="\r")
                        timetable_data = await fetchTimetable(client, target_sem) 
                        print(f"   {Fore.GREEN}    -> Timetable Synced!    ")

                        # 3. Re-fetch Attendance (if you cache it globally, otherwise skip)
                        print(f"   {Fore.CYAN}    -> Fetching Attendance...", end="\r")
                        attendance_data = await fetchAttendance(client, target_sem)
                        print(f"   {Fore.GREEN}    -> Attendance Synced!    ")
                        
                        # 4. Re-fetch Marks (if you cache it globally, otherwise skip)
                        print(f"   {Fore.CYAN}    -> Fetching Marks...", end="\r")
                        marks_data = await fetchMarks(client, target_sem)
                        print(f"   {Fore.GREEN}    -> Marks Synced!       ")

                        print(f"\n   {Fore.GREEN}[✓] All data successfully synchronized!{Style.RESET_ALL}")
                        
                        import asyncio
                        await asyncio.sleep(1.5) # Brief pause so they see the success message
                        
                    except Exception as e:
                        print(f"\n   {Fore.RED}[x] Sync failed: {e}{Style.RESET_ALL}")
                        await asyncio.sleep(2)
                        
                    continue
                
                if choice == '0':
                    print(f"{PEACH}Logging out... Goodbye!")
                    return 
                 
                elif choice == '1': 
                    if not target_sem:
                        print(f"   {Fore.RED}[!] No semester selected. Use option 14.")
                        continue
                    print_header(f"TODAY'S SCHEDULE - {current_sem_name}")
                    data = await fetchTimetable(client, target_sem)
                    print_today_schedule(data)

                elif choice == '2':
                    if not target_sem:
                        print(f"   {Fore.RED}[!] No semester selected. Use option 14.")
                        continue
                    print_header(f"FULL TIMETABLE - {current_sem_name}")
                    data = await fetchTimetable(client, target_sem)
                    print_timetable(data)

                elif choice == '3':
                    if not target_sem:
                        print(f"   {Fore.RED}[!] No semester selected. Use option 14.")
                        continue
                        
                    while True:
                        print(f"\n   {Fore.CYAN}--- ATTENDANCE MENU ---")
                        print(f"   {Fore.WHITE}1. View Summary (All Subjects)")
                        print(f"   {Fore.WHITE}2. View Detailed Attendance (Subject-wise)")
                        print(f"   {Fore.RED}0. Back to Main Menu")
                        
                        sub = input(f"\n   {PEACH}Select option: {Fore.WHITE}").strip()
                        
                        if sub == "0":
                            break
                            
                        elif sub in ["1", "2"]:
                            print(f"   {Fore.CYAN}[.] Fetching attendance data...")
                            try:
                                data = await fetchAttendance(client, target_sem)
                                
                                if not data:
                                    print(f"   {PEACH}[!] No attendance data found for this semester.")
                                    continue
                                    
                                if sub == "1":
                                    print_attendance(data)
                                elif sub == "2":
                                    print(f"   {Fore.CYAN}[.] Syncing detailed subject history... (This takes a moment)")
                                    await print_attendance_with_details(client, target_sem, data)
                                    
                            except Exception as e:
                                print(f"   {Fore.RED}[x] Connection error while fetching attendance: {e}")
                                
                        else:
                            print(f"   {Fore.RED}[!] Invalid option. Please enter 1, 2, or 0.")

                elif choice == '4':
                    if not target_sem:
                        print(f"   {Fore.RED}[!] No semester selected. Use option 14.")
                        continue
                    
                    print(f"   {Fore.CYAN}[.] Fetching Course List...")
                    master_courses = await fetchCourseList(client, target_sem)

                    if not master_courses:
                        print(f"   {Fore.RED}[!] No registered courses found for this semester.")
                        continue

                    while True:
                        print_header(f"SELECT COURSE ({len(master_courses)} Found)")
                        for idx, c in enumerate(master_courses):
                            print(f"   {Fore.WHITE}{idx+1}. {Fore.GREEN}{c['code']} : {Fore.WHITE}{c['title'][:40]} - {PEACH}{c['type']}")
                        print(f"   {Fore.RED}0. Back to Main Menu")
                        
                        c_sel = input(f"\n   {PEACH}Select course number: {Fore.WHITE}").strip()
                        if c_sel == '0': break 

                        try:
                            sel_idx = int(c_sel) - 1
                            if 0 <= sel_idx < len(master_courses):
                                selected_course = master_courses[sel_idx]
                                selected_code = selected_course['code']
                                
                                print(f"   {Fore.CYAN}[.] Fetching classes/slots for {selected_code}...")
                                classes = await fetchCourseClasses(client, target_sem, selected_course['generic_class_id'])
                               
                                if not classes:
                                    print(f"   {Fore.RED}[!] No active classes found for {selected_code}.")
                                    continue

                                selected_class = None
                                
                                if len(classes) == 1:
                                    selected_class = classes[0]
                                    import re
                                    fac_clean = re.sub(r'^\d+\s*-\s*', '', selected_class['faculty'])
                                    print(f"   {Fore.GREEN}[+] Auto-selected: SLOT: {selected_class['slot']} | FAC: {fac_clean}")
                                else:
                                    print(f"\n   {PEACH}SELECT COMPONENT FOR {selected_code}:")
                                    print(f"   {Fore.CYAN}{'#':<4} {'SLOT':<17} {'FACULTY NAME'}")
                                    print(f"   {Fore.CYAN}" + "-" * 60)
                                    
                                    current_slot = ""
                                    import re
                                    for i, cls in enumerate(classes):
                                        if cls['slot'] != current_slot:
                                            if current_slot != "": print("")
                                            print(f"   {PEACH}[{cls['slot']}]")
                                            current_slot = cls['slot']

                                        fac_clean = re.sub(r'^\d+\s*-\s*', '', cls['faculty'])
                                        fac_clean = re.sub(r'\s*-[A-Z\s]+$', '', fac_clean).strip()
                                        print(f"       {Fore.WHITE}{i+1:<2}. {fac_clean}")
                                        
                                    print(f"   {Fore.CYAN}" + "-" * 60)
                                    print(f"       {Fore.RED}0 . Cancel")
                                    
                                    cls_sel = input(f"\n   {PEACH}Select component: {Fore.WHITE}").strip()
                                    if cls_sel == '0': continue
                                    try:
                                        cls_idx = int(cls_sel) - 1
                                        if 0 <= cls_idx < len(classes):
                                            selected_class = classes[cls_idx]
                                        else:
                                            print(f"   {Fore.RED}[!] Invalid component selection.")
                                            continue
                                    except ValueError:
                                        print(f"   {Fore.RED}[!] Please enter a number.")
                                        continue

                                if not selected_class['erp_id']:
                                    print(f"\n   {PEACH}[!] Faculty ID could not be scraped for {selected_code}.")
                                    manual_id = input(f"   {PEACH}Enter Faculty ID (erpId) manually: {Fore.WHITE}").strip()
                                    if manual_id: 
                                        selected_class['erp_id'] = manual_id
                                    else:
                                        print(f"   {Fore.RED}[x] Cannot proceed without Faculty ID.")
                                        continue

                                print(f"   {Fore.CYAN}[.] Fetching materials page...")
                                c_page = await fetchCoursePage(
                                    client, 
                                    target_sem, 
                                    selected_class['class_id'], 
                                    selected_class['erp_id']
                                )
                                
                                print_course_page_table(c_page)
                                
                                import os
                                import glob
                                home = os.path.expanduser("~")
                                save_dir = os.path.join(home, "Downloads")

                                def check_exists(base_name):
                                    safe_name = re.sub(r'[\\/*?:"<>|]', "", base_name).strip()
                                    if not safe_name: safe_name = "downloaded_material"
                                    return len(glob.glob(os.path.join(save_dir, f"{safe_name}.*"))) > 0

                                def format_general_name(code, title, index):
                                    t_lower = title.lower()
                                    if "syllabus" in t_lower:
                                        return f"{code}-syllabus"
                                    elif "reference-material" in t_lower or "reference material" in t_lower:
                                        match = re.search(r'reference[- ]material[- _]*([ivxIVX\d]+)', t_lower)
                                        if match:
                                            numeral = match.group(1).upper()
                                            return f"{code}- Reference material - {numeral}"
                                        return f"{code}- Reference material - {index}"
                                    else:
                                        return f"{code}-{title[:30]}"

                                while True:
                                    print(f"\n   {PEACH}ACTIONS:")
                                    print(f"   {Fore.WHITE}[1, 2..] Enter S.No(s) to download")
                                    print(f"   {Fore.WHITE}[G1, G2] Enter G1, G2.. to download General Material")
                                    print(f"   {Fore.WHITE}[A]      Download ALL materials")
                                    print(f"   {Fore.RED}[0]      Back to Subject List") 
                                    
                                    dl_choice = input(f"\n   {PEACH}Choice: {Fore.WHITE}").strip().upper()
                                    if dl_choice == '0': break 
                                    
                                    def get_short_date(date_str):
                                        if not date_str: return "UnknownDate"
                                        parts = date_str.split('-')
                                        return f"{parts[0]}-{parts[1]}" if len(parts) >= 2 else date_str

                                    if dl_choice == 'A':
                                        count = 0
                                        skipped = 0
                                        print(f"   {Fore.CYAN}[.] Saving files directly to: {save_dir}")
                                        
                                        for lec in c_page['lectures']:
                                            short_date = get_short_date(lec.get('date', ''))
                                            safe_topic = re.sub(r'[\\/*?:"<>|]', "", lec['topic']).strip()
                                            
                                            if lec.get('download_path'):
                                                fname = f"{short_date}_{selected_code}_{safe_topic}"
                                                if check_exists(fname):
                                                    print(f"   {PEACH}[-] Skipped (Exists): {fname[:60]}...")
                                                    skipped += 1
                                                else:
                                                    res, _ = await download_course_material(client, lec['download_path'], save_dir, fname)
                                                    if res: count += 1
                                            
                                            for r_idx, r_path in enumerate(lec.get('ref_paths', [])):
                                                fname = f"{short_date}_{selected_code}_{safe_topic}_Ref_{r_idx+1}"
                                                if check_exists(fname):
                                                    print(f"   {PEACH}[-] Skipped (Exists): {fname[:60]}...")
                                                    skipped += 1
                                                else:
                                                    res, _ = await download_course_material(client, r_path, save_dir, fname)
                                                    if res: count += 1
                                            
                                            if lec.get('web_links'):
                                                print(f"\n   {Fore.BLUE}[LINK] Web Links for: {lec['topic'][:50]}...")
                                                for link in lec['web_links']:
                                                    print(f"        -> {link}")
                                                print("") 
                                                
                                        for i, gen in enumerate(c_page.get('general', [])):
                                            fname = format_general_name(selected_code, gen['title'], i+1)
                                            if check_exists(fname):
                                                print(f"   {PEACH}[-] Skipped (Exists): {fname[:60]}...")
                                                skipped += 1
                                            else:
                                                res, _ = await download_course_material(client, gen['download_path'], save_dir, fname)
                                                if res: count += 1
                                        
                                        print(f"   {Fore.GREEN}[✓] Downloaded {count} new files. (Skipped {skipped})")
                                                
                                    elif dl_choice.startswith('G'):
                                        try:
                                            g_idx = int(dl_choice[1:]) - 1
                                            if 0 <= g_idx < len(c_page['general']):
                                                item = c_page['general'][g_idx]
                                                fname = format_general_name(selected_code, item['title'], g_idx+1)
                                                
                                                if check_exists(fname):
                                                    print(f"   {PEACH}[-] File already exists: {fname}")
                                                else:
                                                    print(f"   {Fore.CYAN}[.] Downloading {fname[:60]}...")
                                                    res, filepath = await download_course_material(client, item['download_path'], save_dir, fname)
                                                    if res: print(f"   {Fore.GREEN}[✓] Saved to: {filepath}")
                                                    else: print(f"   {Fore.RED}[x] Failed: {filepath}")
                                            else:
                                                print(f"   {Fore.RED}[!] Invalid G number.")
                                        except ValueError: 
                                            print(f"   {Fore.RED}[!] Invalid input format.")

                                    elif all(part.strip().isdigit() for part in dl_choice.split(',')):
                                        choices = [x.strip() for x in dl_choice.split(',')]
                                        
                                        for choice in choices:
                                            target_sno = int(choice)
                                            target_lec = next((l for l in c_page['lectures'] if l['s_no'] == target_sno), None)
                                            
                                            if target_lec:
                                                short_date = get_short_date(target_lec.get('date', ''))
                                                safe_topic = re.sub(r'[\\/*?:"<>|]', "", target_lec['topic']).strip()
                                                downloads_started = False
                                                
                                                if target_lec.get('download_path'):
                                                    downloads_started = True
                                                    fname = f"{short_date}_{selected_code}_{safe_topic}"
                                                    if check_exists(fname): 
                                                        print(f"   {PEACH}[-] Main file exists: {fname[:60]}...")
                                                    else:
                                                        print(f"   {Fore.CYAN}[.] Downloading: {fname[:60]}...")
                                                        res, filepath = await download_course_material(client, target_lec['download_path'], save_dir, fname)
                                                        if res: print(f"   {Fore.GREEN}[✓] Saved: {filepath}")
                                                
                                                for r_idx, r_path in enumerate(target_lec.get('ref_paths', [])):
                                                    downloads_started = True
                                                    fname = f"{short_date}_{selected_code}_{safe_topic}_Ref_{r_idx+1}"
                                                    if check_exists(fname): 
                                                        print(f"   {PEACH}[-] Reference exists: {fname[:60]}...")
                                                    else:
                                                        print(f"   {Fore.CYAN}[.] Downloading Reference {r_idx+1}...")
                                                        res, filepath = await download_course_material(client, r_path, save_dir, fname)
                                                        if res: print(f"   {Fore.GREEN}[✓] Saved: {filepath}")
                                                        
                                                if target_lec.get('web_links'):
                                                    downloads_started = True
                                                    print(f"\n   {Fore.BLUE}[LINK] Web Links for Lecture {target_sno}:")
                                                    for link in target_lec['web_links']:
                                                        print(f"        -> {link}")
                                                
                                                if not downloads_started:
                                                    print(f"   {PEACH}[!] No materials available for Lecture {target_sno}.")
                                            else:
                                                print(f"   {Fore.RED}[!] Lecture S.No {target_sno} not found.")
                                    else:
                                        print(f"   {Fore.RED}[!] Invalid command.")
                        except ValueError:
                            print(f"   {Fore.RED}[!] Please enter a valid number.")

                elif choice == '5': 
                    if not target_sem:
                        print(f"   {Fore.RED}[!] No semester selected. Use option 14.")
                        continue
                    print_header(f"INTERNAL MARKS - {current_sem_name}")
                    data = await fetchMarks(client, target_sem)
                    print_marks(data)

                elif choice == '6':
                    if not target_sem:
                        print(f"   {Fore.RED}[!] No semester selected. Use option 14.")
                        continue
                    print_header(f"EXAM SCHEDULE - {current_sem_name}")
                    data = await fetchExamSchedule(client, target_sem)
                    print_exam_schedule(data)

                elif choice == '7':
                    print_header("ACADEMIC TRANSCRIPT")
                    g_data = await fetchGradeHistory(client)
                    print_grade_history(g_data)

                elif choice == '8': 
                    if not target_sem:
                        print(f"   {Fore.RED}[!] No semester selected. Use option 14.")
                        input(f"\n   {PEACH}Press Enter to return...")
                        continue
                        
                    print(f"   {Fore.CYAN}[.] Fetching Digital Assignment Courses...")
                    da_courses = await fetchDACourseList(client, target_sem)
                    
                    if not da_courses:
                        print(f"   {Fore.RED}[!] No digital assignments found for this semester.")
                        input(f"\n   {PEACH}Press Enter to return...")
                        continue
                        
                    while True:
                        import os
                        os.system('cls' if os.name == 'nt' else 'clear')
                        print_header("DIGITAL ASSIGNMENTS")
                        print(f"   {Fore.CYAN}{'#':<3} {'CODE':<10} {'COURSE TITLE':<40} {'FACULTY'}")
                        print(f"   {Fore.CYAN}" + "─" * 95)
                        
                        for i, c in enumerate(da_courses):
                            title = (c['title'][:37] + '..') if len(c['title']) > 37 else c['title']
                            fac = (c['faculty'][:25])
                            print(f"   {Fore.WHITE}{i+1:<3} {Fore.GREEN}{c['code']:<10} {Fore.WHITE}{title:<40} {fac}")
                        
                        print(f"   {Fore.CYAN}" + "─" * 95)
                        print(f"   {Fore.RED}0. Back to Main Menu")
                        
                        c_sel = input(f"\n   {PEACH}Select course number: {Fore.WHITE}").strip()
                        if c_sel == '0': break
                        
                        try:
                            idx = int(c_sel) - 1
                            if 0 <= idx < len(da_courses):
                                selected_course = da_courses[idx]
                                print(f"\n   {Fore.CYAN}[.] Fetching records for {selected_course['code']}...")
                                
                                assignments = await fetchDADetails(client, selected_course['class_id'])
                                
                                if not assignments:
                                    print(f"   {PEACH}[!] No assignments posted yet for {selected_course['code']}.")
                                    input(f"\n   {PEACH}Press Enter to continue...")
                                    continue
                                    
                                while True:
                                    print(f"\n   {PEACH}{Style.BRIGHT}ASSIGNMENTS: {selected_course['code']} - {selected_course['title']}")
                                    print(f"   {Fore.CYAN}{'#':<3} {'TITLE':<25} {'DUE DATE':<15} {'STATUS':<20} {'FILES'}")
                                    print(f"   {Fore.CYAN}" + "─" * 85)
                                    
                                    for asn in assignments:
                                        raw = asn['submission_status']
                                        if not raw: ui_status = f"{PEACH}Pending{Fore.WHITE}"
                                        elif raw == 'File Not Uploaded': ui_status = f"{Fore.RED}Missed{Fore.WHITE}"
                                        else: ui_status = f"{Fore.GREEN}Submitted{Fore.WHITE}"

                                        files = []
                                        if asn['can_qp_download']: files.append("[QP]")
                                        if asn['can_da_download']: files.append("[MY-DA]")
                                        f_str = ", ".join(files) if files else "None"
                                        
                                        print(f"   {Fore.WHITE}{asn['serial_number']:<3} {asn['assignment_title'][:23]:<25} {asn['due_date']:<15} {ui_status:<30} {f_str}")
                                    
                                    print(f"   {Fore.CYAN}" + "─" * 85)
                                    print(f"   {Fore.WHITE}[#] Enter # to Download | [A] Download ALL | {Fore.RED}[0] Go Back")
                                    
                                    a_sel = input(f"\n   {PEACH}Choice: {Fore.WHITE}").strip().upper()
                                    if a_sel == '0': break
                                    
                                    save_dir = os.path.join(os.path.expanduser("~"), "Downloads", "VTOP_Assignments", selected_course['code'])
                                    if not os.path.exists(save_dir): os.makedirs(save_dir)
                                    
                                    to_download = []
                                    if a_sel == 'A':
                                        to_download = assignments
                                    elif a_sel.isdigit():
                                        a_idx = int(a_sel) - 1
                                        if 0 <= a_idx < len(assignments):
                                            to_download = [assignments[a_idx]]
                                    
                                    if not to_download:
                                        print(f"   {Fore.RED}[!] Invalid selection.")
                                        continue

                                    for target_asn in to_download:
                                        if target_asn['can_qp_download']:
                                            fname = f"{target_asn['assignment_title'].replace(' ', '_')}_QP"
                                            print(f"   {Fore.CYAN}[.] Downloading QP: {target_asn['assignment_title']}...")
                                            await download_course_material(client, target_asn['qp_id'], save_dir, fname)
                                        
                                        if target_asn['can_da_download']:
                                            fname = f"{target_asn['assignment_title'].replace(' ', '_')}_Submission"
                                            print(f"   {Fore.CYAN}[.] Downloading Your Submission...")
                                            await download_course_material(client, target_asn['da_id'], save_dir, fname)
                                            
                                    print(f"   {Fore.GREEN}[✓] Done. Files saved to: {save_dir}")
                                    input(f"\n   {PEACH}Press Enter to continue...")
                            else:
                                print(f"   {Fore.RED}[!] Invalid selection.")
                        except ValueError:
                            print(f"   {Fore.RED}[!] Please enter a valid number.")

                elif choice == '9':
                    print_header("ACADEMIC CREDITS DISTRIBUTION")
                    c_data = await fetchCredits(client)
                    print_credits(c_data)

                elif choice == '10': 
                    print_header("GENERAL OUTING SYSTEM")
                    print(f"   {Fore.CYAN}[.] Fetching student details...")
                    data = await fetchGeneralOuting(client)
                    
                    if not data or not data.get('info'):
                        print(f"   {Fore.RED}[!] Could not fetch data. Try logging in again.")
                        continue

                    info = data['info']
                    history = data.get('history', [])

                    print(f"\n   {Fore.WHITE}STUDENT: {Fore.GREEN}{info.get('name')}")
                    print(f"   {Fore.WHITE}BLOCK  : {Fore.CYAN}{info.get('hostelBlock')} {Fore.WHITE}| ROOM: {Fore.CYAN}{info.get('roomNo')}")
                    print(f"   {Fore.CYAN}" + "-" * 60)
                    
                    print(f"\n   {PEACH}MENU:")
                    print(f"   {Fore.WHITE}1. Apply for New Outing")
                    print(f"   {Fore.WHITE}2. View History / Actions")
                    print(f"   {Fore.RED}0. Back")
                    
                    sub = input(f"\n   {PEACH}Select Option: {Fore.WHITE}").strip()
                    
                    if sub == '2':
                        printGeneralOuting(history)
                        if history:
                            print(f"\n   {Fore.WHITE}[P] Download Gate Pass (PDF)")
                            print(f"   {Fore.WHITE}[D] Delete a Request")
                            print(f"   {Fore.RED}[Enter] Go Back")
                            act = input(f"   {PEACH}Choice: {Fore.WHITE}").strip().upper()
                            
                            if act == 'P':
                                try:
                                    idx = int(input(f"   {PEACH}Enter IDX to download: {Fore.WHITE}")) - 1
                                    if 0 <= idx < len(history):
                                        item = history[idx]
                                        if item['download_url']:
                                            print(f"   {Fore.CYAN}[.] Downloading...")
                                            import os
                                            home = os.path.expanduser("~")
                                            download_folder = os.path.join(home, "Downloads")
                                            clean_date = item['out_date'].replace(" ", "-")
                                            filename = f"general_outing_{clean_date}.pdf"
                                            full_path = os.path.join(download_folder, filename)
                                            res, msg = await download_g_outpass(client, item['download_url'], full_path)
                                            if res: print(f"   {Fore.GREEN}[✓] Saved to: {full_path}")
                                            else:   print(f"   {Fore.RED}[x] {msg}")
                                        else:
                                            print(f"   {PEACH}[!] No pass available (Must be Approved).")
                                    else: print(f"   {Fore.RED}[!] Invalid Index.")
                                except ValueError: print(f"   {Fore.RED}[!] Please enter a number.")
                            
                            elif act == 'D':
                                try:
                                    idx = int(input(f"   {PEACH}Enter IDX to delete: {Fore.WHITE}")) - 1
                                    if 0 <= idx < len(history):
                                        item = history[idx]
                                        if "Wait" in item['status'] or "Pending" in item['status']:
                                            if item['booking_id']:
                                                confirm = input(f"   {PEACH}Delete request for {item['place']}? (y/n): {Fore.WHITE}")
                                                if confirm.lower() == 'y':
                                                    res, msg = await deleteGeneralOuting(client, item['booking_id'])
                                                    if res: print(f"   {Fore.GREEN}[✓] {msg}")
                                                    else:   print(f"   {Fore.RED}[x] {msg}")
                                        else: print(f"   {Fore.RED}[!] Cannot delete. (Only 'Waiting' requests can be deleted)")
                                    else: print(f"   {Fore.RED}[!] Invalid Index.")
                                except ValueError: print(f"   {Fore.RED}[!] Please enter a number.")

                    elif sub == '1':
                        print(f"\n   {PEACH}--- NEW OUTING APPLICATION ---")
                        print(f"   {PEACH}[!] NOTE: You must apply at least 24 HOURS in advance.")
                        try:
                            place = input(f"\n   {Fore.WHITE}Place of Visit : {Fore.WHITE}").strip()
                            if place == '0': continue
                            purpose = input(f"   {Fore.WHITE}Purpose        : {Fore.WHITE}").strip()
                            if purpose == '0': continue
                            try:
                                out_d_raw = input(f"   {Fore.WHITE}Out Date (e.g. 3-3-26): {Fore.WHITE}").strip()
                                if out_d_raw == '0': continue
                                out_d = to_vtop_date(out_d_raw)

                                in_d_raw = input(f"   {Fore.WHITE}In Date (e.g. 5-3-26): {Fore.WHITE}").strip()
                                if in_d_raw == '0': continue
                                in_d = to_vtop_date(in_d_raw)
                            except ValueError as e:
                                print(f"   {Fore.RED}[!] {e}")
                                continue
                            if out_d == '0': continue
                            out_t = input(f"   {Fore.WHITE}Out Time (HH:MM): {Fore.WHITE}").strip()
                            in_t  = input(f"   {Fore.WHITE}In Time (HH:MM): {Fore.WHITE}").strip()
                            
                            confirm = input(f"\n   {PEACH}Submit this request? (y/n): {Fore.WHITE}").lower()
                            if confirm == 'y':
                                print(f"\n   {Fore.CYAN}[.] Submitting...")
                                success, msg = await submitGeneralOuting(client, info, place, purpose, out_d, out_t, in_d, in_t)
                                if success: print(f"   {Fore.GREEN}[✓] SUCCESS: {msg}")
                                else: print(f"   {Fore.RED}[x] FAILED: {msg}")
                        except Exception as e: print(f"   {Fore.RED}[!] Error: {e}")

                elif choice == '11': 
                    print_header("WEEKEND OUTING SYSTEM")
                    print(f"   {Fore.CYAN}[.] Fetching details...")
                    data = await fetchWeekendOuting(client)
                    if not data:
                        print(f"   {Fore.RED}[!] Could not fetch data. (Check internet or re-login)")
                        continue

                    info = data.get('info', {})
                    history = data.get('history', [])
                    can_apply = data.get('can_apply', True)

                    print(f"\n   {Fore.WHITE}STUDENT: {Fore.GREEN}{info.get('name')}")
                    print(f"   {Fore.WHITE}BLOCK  : {Fore.CYAN}{info.get('hostelBlock')} {Fore.WHITE}| ROOM: {Fore.CYAN}{info.get('roomNo')}")
                    
                    if not can_apply: print(f"   {Fore.WHITE}STATUS : {Fore.RED}Applications Closed (Tue-Fri Only)")
                    else: print(f"   {Fore.WHITE}STATUS : {Fore.GREEN}Applications Open")
                    
                    print(f"   {Fore.CYAN}" + "-" * 60)
                    while True:
                        print(f"\n   {PEACH}MENU:")
                        print(f"   {Fore.WHITE}1. Apply for Weekend Outing")
                        print(f"   {Fore.WHITE}2. View History / Actions")
                        print(f"   {Fore.RED}0. Back")
                        
                        sub = input(f"\n   {PEACH}Select Option: {Fore.WHITE}").strip()
                        if sub == '0': break
                        
                        if sub == '1':
                            if not can_apply:
                                print(f"\n   {Fore.RED}[!] ACCESS DENIED: Time Restriction")
                                input(f"   {PEACH}Press Enter to return...")
                                continue
                            
                            try:
                                places = ["Vijayawada", "Guntur", "Tenali", "Eluru", "Others"]
                                print(f"\n   {Fore.CYAN}Select Place of Visit:")
                                for i, p in enumerate(places): print(f"   {Fore.WHITE}{i+1}. {p}")
                                p_idx = input(f"   {PEACH}Choice: {Fore.WHITE}").strip()
                                if p_idx == '0': continue
                                place = places[int(p_idx) - 1]
                                
                                purpose = input(f"\n   {PEACH}Purpose (Max 20 chars): {Fore.WHITE}").strip()
                                if purpose == '0': continue
                                # AFTER
                                try:
                                    out_d_raw = input(f"   {PEACH}Date (e.g. 3-3-26): {Fore.WHITE}").strip()
                                    if out_d_raw == '0': continue
                                    out_d = to_vtop_date(out_d_raw)
                                except ValueError as e:
                                    print(f"   {Fore.RED}[!] {e}")
                                    continue
                                if out_d == '0': continue                               
                                times = ["9:30 AM- 3:30PM", "10:30 AM- 4:30PM", "11:30 AM- 5:30PM", "12:30 PM- 6:30PM"]
                                print(f"\n   {Fore.CYAN}Select Outing Time:")
                                for i, t in enumerate(times): print(f"   {Fore.WHITE}{i+1}. {t}")
                                t_idx = input(f"   {PEACH}Choice: {Fore.WHITE}").strip()
                                if t_idx == '0': continue
                                out_t = times[int(t_idx) - 1]
                                
                                import re
                                while True:
                                    contact = input(f"\n   {PEACH}Contact No (10 digits): {Fore.WHITE}").strip()
                                    if contact == '0': break
                                    if re.match(r"^[7-9]\d{9}$", contact): break
                                    else: print(f"   {Fore.RED}[!] Invalid format.")
                                if contact == '0': continue
                                
                                confirm = input(f"\n   {PEACH}Submit request for {place}? (y/n): {Fore.WHITE}").lower()
                                if confirm == 'y':
                                    print(f"\n   {Fore.CYAN}[.] Submitting payload...")
                                    success, msg = await submitWeekendOuting(client, info, place, purpose, out_d, out_t, contact)
                                    if success: print(f"   {Fore.GREEN}[✓] SUCCESS: {msg}")
                                    else: print(f"   {Fore.RED}[x] FAILED: {msg}")
                            except Exception as e: print(f"   {Fore.RED}[!] Error: {e}")

                        elif sub == '2':
                            printWeekendOuting(history)
                            if history:
                                print(f"\n   {Fore.WHITE}[#] Type Row Number to Download Outpass")
                                print(f"   {Fore.WHITE}[D] Delete a Pending Request")
                                print(f"   {Fore.RED}[0] Go Back")
                                act = input(f"\n   {PEACH}Choice: {Fore.WHITE}").strip().upper()
                                
                                if act == '0' or act == '': continue
                                elif act.upper() == 'D':
                                    try:
                                        idx = int(input(f"   {PEACH}Enter Row # to delete: {Fore.WHITE}")) - 1
                                        if 0 <= idx < len(history):
                                            item = history[idx]
                                            if "Wait" in item['status'] or "Pending" in item['status']:
                                                if item.get('booking_id'):
                                                    res, msg = await deleteWeekendOuting(client, item['booking_id'])
                                                    if res: print(f"   {Fore.GREEN}[✓] {msg}")
                                                    else:   print(f"   {Fore.RED}[x] {msg}")
                                            else: print(f"   {Fore.RED}[!] Cannot delete active requests.")
                                    except ValueError: print(f"   {Fore.RED}[!] Please enter a valid number.")
                                        
                                elif act.isdigit():
                                    idx = int(act) - 1
                                    if 0 <= idx < len(history):
                                        selected_outing = history[idx]
                                        if selected_outing['download_link']:
                                            import os
                                            save_dir = os.path.join(os.path.expanduser("~"), "Downloads")
                                            fname = f"Outpass_{selected_outing['out_date']}_{selected_outing['place']}"
                                            print(f"   {Fore.CYAN}[.] Securing Outpass from VTOP servers...")
                                            res, path = await download_w_outpass(client, selected_outing['download_link'], save_dir, fname)
                                            if res: print(f"   {Fore.GREEN}[✓] Saved to: {path}")
                                            else: print(f"   {Fore.RED}[x] Failed to download Outpass.")
                                        else: print(f"   {PEACH}[!] Outpass is not available yet.")

                elif choice == '12':
                    print_header("75% ATTENDANCE CALCULATOR")
                    try:
                        import math
                        target = 75.0
                        present = int(input(f"   {PEACH}Classes Attended (Present): {Fore.WHITE}").strip())
                        total = int(input(f"   {PEACH}Total Classes Conducted:    {Fore.WHITE}").strip())
                        
                        if total == 0: continue
                        current_pct = (present / total) * 100
                        print(f"   {Fore.CYAN}" + "─" * 60)
                        print(f"   {Fore.WHITE}Current Attendance: {Fore.CYAN}{current_pct:.2f}%")
                        
                        if current_pct >= target:
                            bunkable = math.floor((100 * present - target * total) / target)
                            if bunkable > 0:
                                print(f"   {Fore.GREEN}[OK] You are SAFE! You can bunk {int(bunkable)} next classes.")
                            else:
                                print(f"   {PEACH}[!] You are on the edge! You cannot miss any more classes.")
                        else:
                            needed = math.ceil((target * total - 100 * present) / (100 - target))
                            print(f"   {Fore.RED}[x] You are in the DANGER ZONE! Attend {int(needed)} next classes continuously.")
                    except ValueError: print(f"   {Fore.RED}[!] Invalid input.")
                    #input(f"\n   {PEACH}Press Enter to return...")

                elif choice == '13':
                    print_header("STUDENT PROFILE")
                    print_profile(profile_data)

                elif choice == '14': 
                    if not available_sems:
                        print(f"   {Fore.CYAN}...No semester data available. Re-scraping...")
                        available_sems = await fetchSemesters(client)
                    if available_sems:
                        print_header("SELECT SEMESTER")
                        for i, s in enumerate(available_sems): print(f"   {Fore.WHITE}{i+1}. {s['name']}")
                        sel = input(f"\n{PEACH}Select a semester number (0 to cancel): {Fore.WHITE}").strip()
                        if sel == '0': continue
                        try:
                            idx = int(sel) - 1
                            if 0 <= idx < len(available_sems):
                                target_sem = available_sems[idx]['id']
                                current_sem_name = available_sems[idx]['name']
                                print(f"{Fore.GREEN}[+] Active Semester set to: {current_sem_name}")
                        except ValueError: pass

                elif choice == '15': 
                    print(f"\n   {PEACH}=======================================")
                    print(f"   {PEACH}[ UPDATE SAVED CREDENTIALS ]")
                    print(f"   {PEACH}=======================================")
                    new_user = input(f"   {PEACH}[>] Enter Registration Number: {Fore.WHITE}").strip().upper()
                    import pwinput
                    new_pass = pwinput.pwinput(prompt=f"   {PEACH}[>] Enter New VTOP Password: {Fore.WHITE}", mask="*").strip()
                    
                    if new_user and new_pass:
                        confirm = input(f"\n   {PEACH}Save new credentials and restart? (y/n): {Fore.WHITE}").strip().lower()
                        if confirm == 'y':
                            with open("credentials.txt", "w") as f:
                                f.write(f"{new_user}\n{new_pass}\n")
                            import os
                            import sys
                            print(f"   {Fore.GREEN}[✓] Credentials updated successfully! Restarting...")
                            os.execv(sys.executable, ['python'] + sys.argv)
                
                elif choice == '16': 
                    try:
                        import json
                        import os
                        from datetime import datetime as dt_obj, timedelta
                        import services
                        import asyncio

                        print(f"\n   {PEACH}{Style.BRIGHT}[ BUNK SIMULATOR ]")
                        current_year = dt_obj.now().year
                        if os.path.exists("bunk_cache.json"):
                            try:
                                with open("bunk_cache.json", "r") as f:
                                    cache_data = json.load(f)
                                    if isinstance(cache_data, dict) and "blocked_dates" in cache_data:
                                        b_dates = cache_data["blocked_dates"]
                                        if b_dates:
                                            today_dt = dt_obj.now().replace(hour=0, minute=0, second=0, microsecond=0)
                                            print(f"   {Fore.CYAN}[i] Upcoming Non-Instructional, Exam Days and Holidays:")
                                            
                                            printed_any = False
                                            for d_str, purpose in b_dates.items():
                                                try:
                                                    event_date = dt_obj.strptime(f"{d_str}-{current_year}", "%d-%m-%Y")
                                                    if event_date >= today_dt:
                                                        day_name = event_date.strftime("%A")
                                                        print(f"       {Fore.WHITE}{d_str} -- {PEACH}{day_name:<9}{Fore.WHITE} -- {purpose}")
                                                        printed_any = True
                                                except Exception:
                                                    pass 
                                                    
                                            if not printed_any:
                                                print(f"       {PEACH}(No upcoming holidays/exams found)")
                                            print(f"   {Fore.CYAN}" + "-"*45)
                            except Exception: pass

                        bunk_input = input(f"   {PEACH}Enter dates (e.g. 21-4, 28-4 to 2-5, 5-5): {Fore.WHITE}").strip()
                        if not bunk_input: continue

                        valid_dates = []
                        try:
                            from services import parse_date
                            current_year = dt.now().year

                            # Split top-level by comma first
                            segments = [s.strip() for s in bunk_input.split(',')]

                            for segment in segments:
                                segment = segment.strip()
                                if not segment:
                                    continue

                                if ' to ' in segment.lower():
                                    # Range: "28-4 to 2-5"
                                    start_str, end_str = [x.strip() for x in segment.lower().split(' to ')]
                                    start_dt = parse_date(start_str, default_year=current_year)
                                    end_dt   = parse_date(end_str,   default_year=current_year)

                                    if end_dt < start_dt:
                                        # Handle year rollover e.g. 28-12 to 2-1
                                        end_dt = parse_date(end_str, default_year=current_year + 1)

                                    if end_dt < start_dt:
                                        print(f"   {Fore.RED}[!] End date is before start date in range: '{segment}'")
                                        valid_dates = []
                                        break

                                    delta = (end_dt - start_dt).days
                                    for i in range(delta + 1):
                                        valid_dates.append(start_dt + timedelta(days=i))
                                else:
                                    # Single date: "21-4"
                                    valid_dates.append(parse_date(segment, default_year=current_year))

                            if not valid_dates:
                                continue

                            # Deduplicate and sort
                            valid_dates = sorted(set(valid_dates))

                        except ValueError as e:
                            print(f"   {Fore.RED}[!] {e}")
                            continue
                        # --- SEMESTER BOUNDARY CHECK ---
                        sem_end_dt = dt_obj(current_year, 5, 19) 
                        if max(valid_dates) > sem_end_dt:
                            print(f"\n   {Fore.RED}[!] Halt: The semester officially ends on 19-05.")
                            print(f"   {Fore.RED}[!] You cannot simulate attendance beyond this date.")
                            continue

                        print(f"\n   {Fore.CYAN}[.] Fetching timetable...")
                        timetable_data = await fetchTimetable(client, target_sem)
                        print(f"   {Fore.CYAN}[.] Fetching attendance...")
                        attendance_data = await fetchAttendance(client, target_sem)

                        if not timetable_data or not attendance_data:
                            print(f"   {Fore.RED}[x] Data fetch failed. Cannot run simulation.")
                            continue

                        print(f"   {Fore.CYAN}[.] Syncing exact timelines for subjects... (Takes a few seconds)")
                        for sub in attendance_data:
                            c_id = sub.get('course_id')
                            type_id = sub.get('type_id') or sub.get('type_code')
                            sub['exact_last_date'] = None 
                            if c_id and type_id:
                                try:
                                    history = await fetchAttendanceDetail(client, target_sem, c_id, type_id)
                                    if history:
                                        def p_date(x):
                                            try: return dt_obj.strptime(x['date'], "%d-%b-%Y")
                                            except:
                                                try: return dt_obj.strptime(x['date'], "%d-%m-%Y")
                                                except: return dt_obj.min
                                        
                                        history.sort(key=p_date)
                                        sub['exact_last_date'] = history[-1].get('date') 
                                        
                                    await asyncio.sleep(0.4)
                                except Exception: pass

                        academic_calendar_blocks = {}
                        if os.path.exists("bunk_cache.json"):
                            try:
                                with open("bunk_cache.json", "r") as f:
                                    cache_data = json.load(f)
                                    if isinstance(cache_data, dict) and "blocked_dates" in cache_data:
                                        for date_str, reason in cache_data["blocked_dates"].items():
                                            academic_calendar_blocks[date_str] = str(reason)
                            except Exception: pass

                        report = services.simulate_multi_day_bunk(valid_dates, timetable_data, attendance_data, academic_calendar_blocks)
                        print(report)
                        input(f"\n   {PEACH}Press Enter to return to menu...{Fore.WHITE}")
                    except Exception as e: 
                        print(f"   {Fore.RED}[!] Simulation error: {e}")

                elif choice == '17':
                    print_header("OPEN VTOP IN BROWSER")
                    await open_vtop_browser(client)

if __name__ == "__main__":
    check_for_updates()
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        import sys
        # \r moves to the start of the line, \033[K wipes the messy ^C echo
        print(f"\r\033[K\n   {PEACH}[!] Exiting... (Force Quit){Style.RESET_ALL}\n")
        sys.exit(0)