from .general import submit_general_outing_request, fetch_general_outing_requests
from .weekend import submit_weekend_outing_request, fetch_weekend_outing_requests

from .model.general_outing_model import GeneralOutingModel
from .model.weekend_outing_model import WeekendOutingModel
